import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const AI_DETECTION_PROMPT = `You are an expert AI-generated content detector and academic plagiarism analyst.

Analyze the provided text and determine the likelihood that it was generated by AI (e.g., ChatGPT, Gemini, Claude, etc.) versus written by a human.

Evaluate these linguistic signals:
1. **Repetitive phrasing patterns** - AI tends to reuse sentence structures and transitions
2. **Vocabulary uniformity** - AI text often has unnaturally consistent vocabulary level
3. **Hedging and qualifiers** - AI overuses phrases like "it is important to note", "furthermore", "in conclusion"
4. **Lack of personal voice** - AI writing lacks genuine personal anecdotes, unique perspectives, or emotional authenticity
5. **Perfect structure** - AI-generated text is often too well-organized with predictable paragraph structures
6. **Burstiness** - Human writing varies sentence length and complexity; AI tends to be uniform
7. **Perplexity** - Human text has more surprising word choices; AI is more predictable
8. **Cliché density** - AI uses more academic clichés and filler phrases
9. **Citation authenticity** - Check if references seem fabricated or generic
10. **Topic coherence vs. depth** - AI covers topics broadly but often lacks deep, specific insights

Return EXACTLY this JSON structure (no markdown, no explanation, just JSON):
{
  "overallAiScore": <number 0-100, where 100 = definitely AI-generated>,
  "humanScore": <number 0-100, where 100 = definitely human-written>,
  "confidence": "<low | medium | high>",
  "verdict": "<one of: Likely Human-Written | Possibly AI-Assisted | Likely AI-Generated | Highly Likely AI-Generated>",
  "signals": {
    "repetitivePatterns": { "score": <0-100>, "evidence": "<specific examples from text>" },
    "vocabularyUniformity": { "score": <0-100>, "evidence": "<specific examples>" },
    "hedgingOveruse": { "score": <0-100>, "evidence": "<specific examples>" },
    "lackOfPersonalVoice": { "score": <0-100>, "evidence": "<specific examples>" },
    "structurePredictability": { "score": <0-100>, "evidence": "<specific examples>" },
    "burstiness": { "score": <0-100>, "evidence": "<low burstiness = more AI-like>" },
    "perplexity": { "score": <0-100>, "evidence": "<low perplexity = more AI-like>" },
    "clicheDensity": { "score": <0-100>, "evidence": "<specific clichés found>" },
    "citationAuthenticity": { "score": <0-100>, "evidence": "<suspicious references if any>" },
    "depthVsBreadth": { "score": <0-100>, "evidence": "<specific examples>" }
  },
  "flaggedPassages": [
    { "text": "<exact quote from thesis>", "reason": "<why this passage seems AI-generated>" }
  ],
  "summary": "<2-3 sentence overall assessment focusing on the strongest signals>"
}

Scoring guide:
- 0-25: Likely Human-Written
- 26-50: Possibly AI-Assisted
- 51-75: Likely AI-Generated
- 76-100: Highly Likely AI-Generated

Be thorough but fair. Academic writing can sometimes resemble AI output due to formal conventions. Consider the discipline and context.`;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, text } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    if (!text || typeof text !== "string" || text.trim().length < 100) {
      return new Response(JSON.stringify({ error: "Text must be at least 100 characters" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const userMessage = `Analyze the following thesis titled "${title || "Untitled"}" for AI-generated content:\n\n${text}`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: AI_DETECTION_PROMPT },
          { role: "user", content: userMessage },
        ],
        stream: false,
      }),
    });

    if (!response.ok) {
      const status = response.status;
      if (status === 429) {
        return new Response(JSON.stringify({ error: "Rate limited" }), {
          status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (status === 402) {
        return new Response(JSON.stringify({ error: "Payment required" }), {
          status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const t = await response.text();
      console.error("AI gateway error:", status, t);
      return new Response(JSON.stringify({ error: "AI gateway error" }), {
        status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();
    let content = data.choices?.[0]?.message?.content || "";
    content = content.replace(/^```json\s*\n?/, "").replace(/\n?```\s*$/, "").trim();

    const result = JSON.parse(content);

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("detect-ai error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
