import { useState } from "react";
import { ClipboardCheck, Loader2, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

interface ScoreData {
  scores: Record<string, { score: number; max: number; justification: string }>;
  totalScore: number;
  recommendation: string;
  overallComments: string;
}

interface ScoreSheetButtonProps {
  title: string;
  text: string;
  format: string;
}

const CRITERIA_LABELS: Record<string, string> = {
  thesisTitle: "Thesis/Project Title",
  researchProblem: "Research Problem",
  researchObjectives: "Research Objectives",
  literatureReview: "Literature Review",
  researchMethodology: "Research Methodology",
  originality: "Originality",
  referencing: "Referencing",
  format: "Format",
  presentationLanguageStyle: "Presentation/Language/Style",
  resultsAndFindings: "Results and Findings",
  summaryConclusions: "Summary, Conclusions & Recommendations",
};

const generateScoreSheetHTML = (title: string, data: ScoreData): string => {
  const rows = Object.entries(CRITERIA_LABELS)
    .map(([key, label], i) => {
      const item = data.scores[key];
      if (!item) return "";
      return `
        <tr>
          <td style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:13px;">${i + 1}</td>
          <td style="padding:8px 12px;border:1px solid #ccc;font-size:13px;">${label}</td>
          <td style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:13px;">${item.max}</td>
          <td style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:13px;font-weight:bold;">${item.score}</td>
          <td style="padding:8px 12px;border:1px solid #ccc;font-size:12px;color:#555;">${item.justification}</td>
        </tr>`;
    })
    .join("");

  return `
    <div style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;">
      <div style="text-align:center;margin-bottom:24px;">
        <h1 style="font-size:18px;margin:0 0 4px;">Kirinyaga University</h1>
        <h2 style="font-size:15px;font-weight:600;margin:0 0 4px;color:#333;">BOARD OF POSTGRADUATE STUDIES</h2>
        <h3 style="font-size:14px;font-weight:600;margin:0;color:#555;">EVALUATION OF POSTGRADUATE RESEARCH THESIS/PROJECT</h3>
      </div>

      <div style="margin-bottom:16px;font-size:13px;">
        <p style="margin:4px 0;"><strong>Thesis Title:</strong> ${title}</p>
      </div>

      <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">
        <thead>
          <tr style="background:#f0f0f0;">
            <th style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:13px;width:40px;">S/No</th>
            <th style="padding:8px 12px;border:1px solid #ccc;text-align:left;font-size:13px;">Item</th>
            <th style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:13px;width:60px;">Max</th>
            <th style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:13px;width:60px;">Score</th>
            <th style="padding:8px 12px;border:1px solid #ccc;text-align:left;font-size:13px;">Justification</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
          <tr style="background:#f0f0f0;font-weight:bold;">
            <td colspan="2" style="padding:8px 12px;border:1px solid #ccc;font-size:13px;text-align:right;">TOTAL</td>
            <td style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:13px;">100</td>
            <td style="padding:8px 12px;border:1px solid #ccc;text-align:center;font-size:14px;">${data.totalScore}</td>
            <td style="padding:8px 12px;border:1px solid #ccc;font-size:13px;"></td>
          </tr>
        </tbody>
      </table>

      <div style="margin-bottom:16px;padding:12px 16px;border:2px solid #333;border-radius:6px;">
        <p style="margin:0 0 8px;font-size:14px;font-weight:bold;">Recommendation:</p>
        <p style="margin:0;font-size:15px;font-weight:bold;color:${
          data.recommendation.includes("without") ? "#16a34a" :
          data.recommendation.includes("minor") ? "#ca8a04" :
          data.recommendation.includes("major") ? "#ea580c" : "#dc2626"
        };">✓ ${data.recommendation}</p>
      </div>

      <div style="margin-top:16px;padding:12px 16px;background:#f9f9f9;border-radius:6px;">
        <p style="margin:0 0 6px;font-size:13px;font-weight:bold;">Overall Comments:</p>
        <p style="margin:0;font-size:13px;color:#444;line-height:1.5;">${data.overallComments}</p>
      </div>

      <div style="margin-top:32px;font-size:12px;color:#888;border-top:1px solid #ddd;padding-top:12px;">
        <p style="margin:2px 0;">Generated by ScholarReview AI · ${new Date().toLocaleDateString()}</p>
        <p style="margin:2px 0;font-style:italic;">KyU is ISO 9001:2015 Certified</p>
      </div>
    </div>
  `;
};

const ScoreSheetButton = ({ title, text, format }: ScoreSheetButtonProps) => {
  const [isScoring, setIsScoring] = useState(false);
  const [scoreData, setScoreData] = useState<ScoreData | null>(null);

  const handleScore = async () => {
    setIsScoring(true);
    try {
      const resp = await fetch(`${SUPABASE_URL}/functions/v1/score-thesis`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ title, text, format }),
      });

      if (!resp.ok) {
        const err = await resp.json().catch(() => ({}));
        toast.error(err.error || "Failed to generate score sheet.");
        return;
      }

      const data: ScoreData = await resp.json();
      setScoreData(data);
      toast.success(`Score: ${data.totalScore}/100 — ${data.recommendation}`);

      // Auto-download PDF
      await downloadPDF(data);
    } catch (err) {
      console.error("Scoring error:", err);
      toast.error("An error occurred while scoring. Please try again.");
    } finally {
      setIsScoring(false);
    }
  };

  const downloadPDF = async (data: ScoreData) => {
    toast.info("Generating PDF score sheet...");
    const html = generateScoreSheetHTML(title, data);

    const container = document.createElement("div");
    container.innerHTML = html;
    document.body.appendChild(container);

    try {
      const html2pdf = (await import("html2pdf.js")).default;
      await html2pdf()
        .set({
          margin: [0.4, 0.5, 0.4, 0.5],
          filename: `${title.replace(/[^a-zA-Z0-9]/g, "_")}_ScoreSheet.pdf`,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: "in", format: "a4", orientation: "portrait" },
        })
        .from(container)
        .save();
      toast.success("Score sheet PDF downloaded!");
    } catch {
      toast.error("Failed to generate PDF.");
    } finally {
      document.body.removeChild(container);
    }
  };

  return (
    <div className="flex flex-col items-center gap-2">
      <Button
        onClick={handleScore}
        disabled={isScoring}
        variant="outline"
        className="gap-2"
      >
        {isScoring ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Scoring...
          </>
        ) : (
          <>
            <ClipboardCheck className="w-4 h-4" />
            {scoreData ? "Re-score & Download" : "Generate Score Sheet (PDF)"}
          </>
        )}
      </Button>
      {scoreData && !isScoring && (
        <p className="text-xs text-muted-foreground font-sans">
          Score: <span className="font-semibold text-foreground">{scoreData.totalScore}/100</span> — {scoreData.recommendation}
        </p>
      )}
    </div>
  );
};

export default ScoreSheetButton;
